apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: comdirect-db-credentials
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/apps/items/comdirect-db-credentials"
