apiVersion: v1
kind: Service
metadata:
  name: gizmosql
spec:
  type: ClusterIP
  selector:
    app: gizmosql
  ports:
    - name: flight
      port: 31337
      targetPort: flight
      protocol: TCP
