resources:
  - ../home-blog/

nameSuffix: -public

patches:
  - path: public-deployment.yaml
    target:
      kind: Deployment
      name: home-blog
  - path: public-service.yaml
    target:
      kind: Service
      name: home-blog
