apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-blog
spec:
  selector:
    matchLabels:
      app: home-blog-public
  template:
    metadata:
      labels:
        app: home-blog-public
    spec:
      containers:
        - name: home-blog
          env:
            - name: BLOG_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: home-blog-app
                  key: fqdn-uri
            - name: FEATURES
              $patch: replace
              value: ""
            - name: BASE_URL
              $patch: replace
              value: "https://blog.jonathanschwarzhaupt.net"
      initContainers:
        - name: db-migrations
          env:
            - name: BLOG_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: home-blog-app
                  key: fqdn-uri
