apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5b2s9Q5AufVX+3G29JpYUqGZIBXKOUHnDXfHow==,iv:jwRe53EgSwSSKt94k3NlKqXF/gSXEJgJ71gsFoMhrUU=,tag:K7/zZf7JjMWtsg2koDYjtA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: redis-password
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pcfrqn8tghfjex0r7dfsmyas2j23274f6xv29cffhje8wn3q957s09cvmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMGd3S3ZwMFZPeGlBbUlK
            eXBKcDV5Yk5VN3d5U0RIcnl1eS9uSC9QVEZBCnhoM0FmQUtXaDg1QUM2ZlhqNnBh
            TUJZUUs1UE1QZHEzU1ZIL3NaN3ZVTTgKLS0tIFZMelVGUlFiek5wQXpLcGNHVG1H
            N0ZPdERYOWhJRDY0a3RuOHhjZ0Y2MkkK0TglOaig2Gb3Sehfdx196kOzrdyjtYk8
            qESqCDb80QXdUTuosZ4eRbFGwu4OIaHpP1/Hop4Scsu56OGLtFJ2Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T14:02:34Z"
    mac: ENC[AES256_GCM,data:2u7LvLW7+7iyA8jSKDcf7iS19X5sn3Bj8Ce3ecdUH61g2Tf3TosGakqrsn7Fvf555OjDMruTREy6SvVDeZiM4WAEWOkYqNv1TJES7HxOfDyJVnNHkf958yu24UZTf6MERU7GFnhoV4Rhd/jVV5gtZt9tri53bqOodcIGuD2ScxM=,iv:nzN3LGdce4VOvQJ3gtkK+PzAEAjFrwStk+d9qNmUVTg=,tag:HpTzGoM3OG3fYOTVfqbBPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
