apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: obsidian-livesync
stringData:
    credentials.json: ENC[AES256_GCM,data:/aPAaEGo7OMAZ7st+Z/5+ZUoB9in/K/SZDc2Tqfk1MNNHC7yQGKYMNb5qlzjiO88qXnVRFM4xvoAHNloHKdck0Aq1cfdk98cU3aHFw/xo3AZOTt01JuGy4Sg8f4F6YTM2r7Tk4iJn98emUTGb3LEOugIhtSMnX33CC1fmwjFhz4sboU0BeNfQCXIpd/w5x+HDlxMHgGleq7q//HIZsRxRGSQj2SIhUXT4lOxnfbPXHc=,iv:rGg7LKiZ5aJA15rnpJoCzta6ruQenXATQtWCqsU1l9I=,tag:BT567zCg/Y/tg8qbtXuO2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OEF6RUhocXltRXExdHNn
            d2JBVnVKRTlYU2dOOGMrV09SRWdTK3dueUVNCmVVYkNja2pqaEhyZWJVM3FKdU8v
            NVd4cjZRcXdWamVhVG1CSXY3ZlJPRlEKLS0tIGJka20wOXZsZ09McDdzLzRUUEEr
            MEtzR0R0Uk1PaU9hSkZNeVpuZE5XZkEKvpCs3H6ZVXJk6tboE4/VEYKUqxohRiBy
            /Thszqvhfe1xBGDPFpRJVJvXz6pUx+Rzkr5WpCPNcaeXjsMKWwRQ0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pcfrqn8tghfjex0r7dfsmyas2j23274f6xv29cffhje8wn3q957s09cvmt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T20:38:38Z"
    mac: ENC[AES256_GCM,data:eWHpc4dplCBr1muymoB9PirTe8mushYOPXCXwjuJq92+lakwAnLOaC0PMEo7f6TA9q2TlR1hsoroyASgmHDkT0oH72wuXsztNteNWl+Wk1g8Ls69EyoZKlrTCTZYfEDrFJbhUb9EwgU0yctgF9ukPnExT0ZQlGok7eMtVaYC190=,iv:t6usBGCh0MocW8XRU3uq2xPo2O8sbl71zGeUSTyMD0Q=,tag:kvsmjJ132eV4c93UDdYiMg==,type:str]
    version: 3.13.1
