apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:AoyWdoO7peJRFxf/vrXmqic8rd91bF/iyez66LOdSzrfAW6ZUecA+5q4IZ0nl3zIa7Y1Wd4GdQml32b/JsNgFm/WMVUioEfXJq9qrktvyP9IrqmQiq8hasgyltJJ1alUl+7KpDg1IyWqP5etAesAk7FOAoRWFX20mmR2Ep0gO2i6DaP1oLR0vmCmXUNESplHnm/aWlCJJOcw0479on5lBCrCeBnq08lbTIQEnhjJ+/DHZ6XCB91wesBH0WqL572BCHS3/aM859OcByZKiHvMr0FBCBsdPD55avUqTUh228z/aZtEv4IPjeOTCss=,iv:5gQB5oUC6HTf4ceXfw5IuBoI97JD21ztLYAzvsHux9E=,tag:qj88Ag4OrSef6VFcGH1FKg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZU9NYUhwR00reDJPUkhY
            bmxrMW5jb2hCcUxJZzVtNDQzMnpZbzFkbUFFCnBHYXI4anlJKzBCdEJqdTRJbGIr
            L2d5ZkwwTmNISEJwOXlieUh0bUxnVGMKLS0tICt3dnJqMExzM2paM2huc1phdjN3
            QXNFUnRJMTh5c1NrNFBGcERzeEdrTHcKE9Vds9w70Umw39/NC0ZQtM/DXDqFPb6m
            EwGb1O2wYCqJDwChLz2nFN9SnV5qIMuXsTchewXsWbT8xjbMFbWIQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pcfrqn8tghfjex0r7dfsmyas2j23274f6xv29cffhje8wn3q957s09cvmt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T05:54:43Z"
    mac: ENC[AES256_GCM,data:9rmyH/wUoLTLGXfhXH7g5Kfp0FucV8qILDNjvFCROrPbe5fwG10LMsMDi5t0CnjXBaTiuRj24ZaNKU3+Tzgo5ZUtXbu7gpnwXoZ7kdGuGKQoeON09Lb0bQzlngO+SoTiMLcbWs77uIJcDxDhEU+L8vgRs8TilhI/0rTssT6cyfs=,iv:EltzbwswGSwQ6gGOn/BIpZMIv5+XCBkoD/t6ms49LE0=,tag:OPxz1q2NUFA30pPQCr0viA==,type:str]
    version: 3.13.1
