apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-blog
spec:
  template:
    spec:
      containers:
        - name: home-blog
          image: ghcr.io/jonathanschwarzhaupt/home-blog:v0.2.0
          env:
            - name: FEATURES
              value: ""
              valueFrom: null
      initContainers:
        - name: db-migrations
          image: ghcr.io/jonathanschwarzhaupt/home-blog-migrate:v0.2.0
