apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tailscale-credentials
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/apps/items/tailscale-k8s-operator-oauth"
