apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-blog
resources:
  - ../../base/home-blog-private/
  - ../../base/home-blog-public/
  - database.yaml
  - podmonitor.yaml
  - private-ingress.yaml
  - public-cloudflare-secret.yaml
  - public-cloudflare.yaml
