apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: home-blog-app
  # this is required so the pod monitor is picked up
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: home-blog-public
  podMetricsEndpoints:
    - port: metrics
