apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: home-blog-db-backup
spec:
  cluster:
    name: home-blog
  schedule: "0 0 3 * * *"  # At 3 a.m. every day
  backupOwnerReference: cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
