apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: home-blog-db-backup
spec:
  schedule: "0 0 3 * * *"  # At 3 a.m. every day
  backupOwnerReference: cluster
  cluster:
    name: home-blog
