apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/apps/items/synology-csi-credentials"
