# Default storage class for most workloads
# Use for: databases, app data, SQLite files, general persistent storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  fsType: "ext4"
  dsm: "192.168.178.74"
  location: "/volume2"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
# Retained storage for production databases and critical data
# Use for: PostgreSQL clusters, important data to survive PVC deletion
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-retain
provisioner: csi.san.synology.com
parameters:
  fsType: "ext4"
  dsm: "192.168.178.74"
  location: "/volume2"
reclaimPolicy: Retain # PV persists even after PVC deletion
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
# NFS for shared data across multiple pods
# Use for: shared configs, media files, logs accessed by multiple pods
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-delete
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  dsm: "192.168.178.74"
  location: "/volume2"
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4.1
  - hard # Don't give up on temporary network issues
  - timeo=600 # 60 second timeout
  - retrans=2 # Retry twice before reporting error
reclaimPolicy: Delete
allowVolumeExpansion: true

---
# NFS with retain policy for important shared data
# Use for: shared media libraries, shared configs to keep
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-retain
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  dsm: "192.168.178.74"
  location: "/volume2"
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
reclaimPolicy: Retain
allowVolumeExpansion: true
