apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-pvc
  namespace: default
spec:
  storageClassName: synology-csi-nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
