apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 30m
  # The chart to pull
  chart:
    spec:
      chart: airflow
      version: "1.18.0"
      # The repository to pull the chart from
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: airflow
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
