apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-blog
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: home-blog
  template:
    metadata:
      labels:
        app: home-blog
    spec:
      enableServiceLinks: false
      # TODO: Implement / verify later
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      containers:
        - name: home-blog
          image: ghcr.io/jonathanschwarzhaupt/home-blog:0.3.0-dev.6.98ce139 
          args: 
            - "-features=$(FEATURES)"
          ports:
          - name: app
            containerPort: 4000
          - name: metrics
            containerPort: 9091
          env:
            - name: BLOG_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: home-blog-creds
                  key: BLOG_DB_DSN
            - name: FEATURES
              valueFrom:
                configMapKeyRef:
                  name: home-blog-config
                  key: features
          resources:
            requests:
              cpu: "200m"
              memory: "0.5Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /health
              port: app
            periodSeconds: 5
            failureThreshold: 24  # 5s * 24 = 120s max time allowed to start
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: app
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: app
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
      initContainers:
        - name: db-migrations
          image: ghcr.io/jonathanschwarzhaupt/home-blog-migrate:0.3.0-dev.6.98ce139
          args:
            - "up"
          env:
            - name: BLOG_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: home-blog-creds
                  key: BLOG_DB_DSN
          resources:
            requests:
              cpu: "200m"
              memory: "0.5Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
