apiVersion: kustomize.toolkit.fluxcd.io/va
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: True