apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data-pvc
spec:
  storageClassName: synology-csi-iscsi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
