apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gizmosql
resources:
  - ../../base/gizmosql
  - secret.yaml
  - storage.yaml
  - service_overlay.yaml

patchesStrategicMerge:
  - service_overlay.yaml
