apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-blog
spec:
  template:
    spec:
      containers:
        - name: home-blog
          image: ghcr.io/jonathanschwarzhaupt/home-blog:0.4.0-dev.11.6f493d7
          env:
            - name: FEATURES
              value: ""
              valueFrom: null
      initContainers:
        - name: db-migrations
          image: ghcr.io/jonathanschwarzhaupt/home-blog-migrate:0.4.0-dev.11.6f493d7
