apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-blog
spec:
  template:
    spec:
      containers:
        - name: home-blog
          image: ghcr.io/jonathanschwarzhaupt/home-blog:0.4.1-rc.7.36cef46
      initContainers:
        - name: db-migrations
          image: ghcr.io/jonathanschwarzhaupt/home-blog-migrate:0.4.1-rc.7.36cef46
