apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-blog
spec:
  selector:
    matchLabels:
      app: home-blog-private
  template:
    metadata:
      labels:
        app: home-blog-private
    spec:
      containers:
        - name: home-blog
          image: ghcr.io/jonathanschwarzhaupt/home-blog:0.4.1-rc.10.71fafb9
          env:
            - name: BLOG_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: home-blog-app
                  key: fqdn-uri
            - name: FEATURES
              value: "admin"
              valueFrom: null
            - name: BASE_URL
              value: "https://blog.jonathanschwarzhaupt.net"
              valueFrom: null
      initContainers:
        - name: db-migrations
          image: ghcr.io/jonathanschwarzhaupt/home-blog-migrate:0.5.0-rc.13.27c485b
          env:
            - name: BLOG_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: home-blog-app
                  key: fqdn-uri
