apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding
  - mealie
  - actualbudget
  - gizmosql
  # - comdirect
  - obsidian-livesync
  - home-blog-admin
  # - airflow
