apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: op-service-account-apps-rw-creds
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/apps/items/op-service-account-apps-rw-creds"
