apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comdirect-data-pvc
spec:
  storageClassName: synology-csi-nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
