apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
    spec:
      containers:
        - name: actualbudget
          image: actualbudget/actual-server:26.5.0
          ports:
            - containerPort: 5006

          livenessProbe:
            exec:
              command:
                - node
                - src/scripts/health-check.js
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - node
                - src/scripts/health-check.js
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10

          env:
            - name: ACTUAL_DATA_DIR
              value: /data

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - mountPath: /data
              name: actualbudget-data

      volumes:
        - name: actualbudget-data
          persistentVolumeClaim:
            claimName: actualbudget-data-pvc
