apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: synology-csi
      interval: 12h
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-client-info

    # Configuration of the default storage classes
    storageClasses:
      # iSCSI storage classes
      iscsi-delete:
        disabled: false
        isDefault: true # Make this the default storage class
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        parameters:
          fsType: "ext4"
          dsm: "192.168.178.74"
          location: "/volume2"

      iscsi-retain:
        disabled: false
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          fsType: "ext4"
          dsm: "192.168.178.74"
          location: "/volume2"

      # NFS storage classes
      nfs-delete:
        disabled: false
        isDefault: false
        reclaimPolicy: Delete
        parameters:
          protocol: "nfs"
          dsm: "192.168.178.74"
          location: "/volume2"
          mountPermissions: "0755"
        mountOptions:
          - nfsvers=4.1
          - hard
          - timeo=600
          - retrans=2

      nfs-retain:
        disabled: false
        isDefault: false
        reclaimPolicy: Retain
        parameters:
          protocol: "nfs"
          dsm: "192.168.178.74"
          location: "/volume2"
          mountPermissions: "0755"
        mountOptions:
          - nfsvers=4.1
          - hard
          - timeo=600
          - retrans=2

      # Disable SMB storage classes since not needed
      smb-delete:
        disabled: true

      smb-retain:
        disabled: true
