apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 24h
  url: https://christian-schlichtherle.github.io/synology-csi-chart
