apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:tze5lTh+xxSIGp6bJVyo3qOYzc4b0klE2r2RCWQFhUZ7bxHIJFM51shqGeJ6T4vtNbklbSWPxHw=,iv:7+rYtRDOGuqEDb40EgRI6LlHIVUULqMTKz41vyf/Ycc=,tag:btKoJ87g45qqrjwhbFIWhg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pcfrqn8tghfjex0r7dfsmyas2j23274f6xv29cffhje8wn3q957s09cvmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN3N0RVNxakRxNTFKTUI3
            U3JHMm1yQnM1SVJ3RjJ3ZlBwRWFjQ0hqM1VvClIxUHFLTCs1SUo1cGsrY21pc1lU
            M2xhaW1YZWRxWTgzZFMwcXdaL1JyeTQKLS0tIEJmV0U0ZXVOR3IvU255WWg5VDd1
            aEVOMDF2VFRhQ1k5L2krQW1MdzB0ejAKmIG6SeXe9MZD4hxIv603rBO3eiLftSbz
            2ocUtnzmozGnkwszOCfHI6QCGV9XH6M/5blrWclFBcj1bN+iaKq3eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T07:04:57Z"
    mac: ENC[AES256_GCM,data:fxq747wGyZC6DbQco3w3TB+a+F8GFv6QmmxPPlr3455xTEP8nG7gb9HB88xOS1zNwFwHViv71n55wZu8fmeu1mcKcB4SoVZ8AINQ1L4cw+Ae1fwfRg13BALcIZK1Up4tSrnMdOSdn9eJG7nuqPgKZeZmQsOE9puEhQ0srAGK9Kw=,iv:OAULyQ+i5Xq6GQhT2hRY1BZeZZG4RcHEN3sDsDBaa28=,tag:LP+Ac8L67+hjGb5O9GHWiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
